[all]
alias = "install"

[install]
phony = true
keep_ts = true
requires = ["poetry.lock"]
commands = [
    "poetry install ${poetry_extra}",
]

[format]
phony = true
requires = ["install"]
commands = [
    "isort .",
    "black .",
]

[lint]
phony = true
requires = ["install"]
commands = [
    "isort --check .",
    "black --check .",
    "flake8 .",
    "mypy .",
]

[tests]
phony = true
requires = ["install"]
commands = [
    "pytest ${pytest_args} ${pytest_path}",
]

["poetry.lock"]
requires = ["pyproject.toml"]
commands = [
    "poetry lock && touch ${.target}",
]
